# Generated by Django 5.0.6 on 2024-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='external',
            name='information',
        ),
        migrations.AddField(
            model_name='external',
            name='city',
            field=models.CharField(default='default-value', max_length=50),
            preserve_default=False,
        ),
    ]
