# Generated by Django 5.0.6 on 2024-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_external_information_external_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='weather_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
